# Generated by Django 4.1.5 on 2023-01-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_friendshipkey_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshipkey',
            old_name='user',
            new_name='username',
        ),
    ]
