# Generated by Django 4.1.5 on 2023-01-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_friendshipkey_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='count_splitters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
